/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package runproyectlogin;
//Hola prueba del cambio 2 holaaa
/**
 *
 * @author alan_
 */
import java.io.FileNotFoundException;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;

import javax.swing.filechooser.FileNameExtensionFilter;

import java.io.File;

import javax.swing.ImageIcon;

import java.awt.Image;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    //Validar correo electronico
    public static boolean esCorreoValido(String correo) {
    String regex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    return correo.matches(regex);
}
    
    //Validar si la contrasenia cumple con los parametros establecidos
    public static boolean validarContrasena(String password) {
    if (password.length() < 8) {
        return false; // Debe tener al menos 8 caracteres
    }
    
    boolean tieneLetra = false;
    boolean tieneNumero = false;
    boolean tieneEspecial = false;
    
    for (char c : password.toCharArray()) {
        if (Character.isLetter(c)) {
            tieneLetra = true;
        } else if (Character.isDigit(c)) {
            tieneNumero = true;
        } else if (!Character.isLetterOrDigit(c)) {
            tieneEspecial = true;
        }
    }
    
    return tieneLetra && tieneNumero && tieneEspecial;
}
    
    //Crear verificacion de si se encuentra el nombre de usuario para crear cuenta
    public static boolean verificarExistencianombreusuario(String nombreusuario) {
        Connection conexion = BasededatosTwitter.conectar();
        if (conexion == null) {
            return false;
        }

        String consulta = "SELECT COUNT(*) FROM usuarios WHERE nombre_usuario = ?"; 

        try {
            PreparedStatement ps = conexion.prepareStatement(consulta);
            ps.setString(1, nombreusuario); // 
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                int count = rs.getInt(1);
                return count > 0; // Si count > 0, el dato ya está registrado
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
    
   
    public login() 
    {
        initComponents();
         b_crearcuenta.setEnabled(false); // Inicialmente deshabilitado hasta marcar los terminos.
         
        //Letras azules boton iniciar sesion
        b_iniciarsesion.setText("Inicia sesión");
        b_iniciarsesion.setBorder(null);
        b_iniciarsesion.setContentAreaFilled(false);
        b_iniciarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_iniciarsesion.addActionListener(new java.awt.event.ActionListener() 
        {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) 
        {
        b_iniciarsesionActionPerformed(evt);
        }
        });

        // Agrega el MouseListener para cambiar el color del texto al pasar el mouse
        b_iniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() 
        {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) 
        {
        // Cambiar el color del texto cuando el mouse pasa por encima
        b_iniciarsesion.setForeground(java.awt.Color.BLUE);
        }
    
        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) 
        {
        // Restaurar el color original cuando el mouse sale
        b_iniciarsesion.setForeground(java.awt.Color.BLACK);
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelizquierdo_login = new javax.swing.JPanel();
        l_texttwitterlogin = new javax.swing.JLabel();
        l_fondoiniciosesion = new javax.swing.JLabel();
        panelderecho_login = new javax.swing.JPanel();
        l_textcraeteaccount = new javax.swing.JLabel();
        l_nombreusuario = new javax.swing.JLabel();
        l_correo = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        tf_nombreusuario = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        b_showpassword = new javax.swing.JButton();
        l1_passwordconditions = new javax.swing.JLabel();
        l2_passwordconditions = new javax.swing.JLabel();
        l1_terminos = new javax.swing.JLabel();
        l2_terminos = new javax.swing.JLabel();
        check_terminos = new javax.swing.JCheckBox();
        b_crearcuenta = new javax.swing.JButton();
        l_iniciarsesion = new javax.swing.JLabel();
        b_iniciarsesion = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        btnSeleccionarFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelizquierdo_login.setBackground(new java.awt.Color(255, 255, 255));
        panelizquierdo_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_texttwitterlogin.setFont(new java.awt.Font("Times New Roman", 2, 60)); // NOI18N
        l_texttwitterlogin.setForeground(new java.awt.Color(255, 255, 255));
        l_texttwitterlogin.setText("Twitter");
        panelizquierdo_login.add(l_texttwitterlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 40));
        panelizquierdo_login.add(l_fondoiniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 460));

        panelderecho_login.setBackground(new java.awt.Color(255, 255, 255));
        panelderecho_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_textcraeteaccount.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l_textcraeteaccount.setText("Create an account");
        panelderecho_login.add(l_textcraeteaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        l_nombreusuario.setText("Nombre de usuario");
        panelderecho_login.add(l_nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        l_correo.setText("Correo");
        panelderecho_login.add(l_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        l_password.setText("Contraseña");
        panelderecho_login.add(l_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        tf_nombreusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreusuarioActionPerformed(evt);
            }
        });
        panelderecho_login.add(tf_nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 278, -1));

        tf_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_correoActionPerformed(evt);
            }
        });
        panelderecho_login.add(tf_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 278, -1));
        panelderecho_login.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 278, -1));

        b_showpassword.setBorder(null);
        b_showpassword.setBorderPainted(false);
        b_showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_showpasswordActionPerformed(evt);
            }
        });
        panelderecho_login.add(b_showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 20, 20));

        l1_passwordconditions.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        l1_passwordconditions.setForeground(new java.awt.Color(153, 153, 153));
        l1_passwordconditions.setText("Usa 8 o mas caracteres con una mezcla de numeros, letras y ");
        panelderecho_login.add(l1_passwordconditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        l2_passwordconditions.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        l2_passwordconditions.setForeground(new java.awt.Color(153, 153, 153));
        l2_passwordconditions.setText("caracteres especiales.");
        panelderecho_login.add(l2_passwordconditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        l1_terminos.setForeground(new java.awt.Color(153, 153, 153));
        l1_terminos.setText("Al crear una cuenta aceptas nuestros");
        panelderecho_login.add(l1_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        l2_terminos.setText("Terminos de uso y políticas de privacidad");
        panelderecho_login.add(l2_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        check_terminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_terminosActionPerformed(evt);
            }
        });
        panelderecho_login.add(check_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        b_crearcuenta.setBackground(new java.awt.Color(237, 186, 250));
        b_crearcuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b_crearcuenta.setForeground(new java.awt.Color(255, 255, 255));
        b_crearcuenta.setText("Crear cuenta");
        b_crearcuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_crearcuenta.setBorderPainted(false);
        b_crearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearcuentaActionPerformed(evt);
            }
        });
        panelderecho_login.add(b_crearcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 136, 35));

        l_iniciarsesion.setText("¿Ya tienes cuenta?");
        panelderecho_login.add(l_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        b_iniciarsesion.setText("Inicia sesión");
        b_iniciarsesion.setBorder(null);
        b_iniciarsesion.setContentAreaFilled(false);
        b_iniciarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iniciarsesionActionPerformed(evt);
            }
        });
        panelderecho_login.add(b_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        lblFoto.setText("mostrar");
        panelderecho_login.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        btnSeleccionarFoto.setText("Selecciona Foto");
        btnSeleccionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarFotoActionPerformed(evt);
            }
        });
        panelderecho_login.add(btnSeleccionarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelizquierdo_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelderecho_login, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelizquierdo_login, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addComponent(panelderecho_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreusuarioActionPerformed

    private void b_showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_showpasswordActionPerformed
        // TODO add your handling code here:
        //MOSTRAR Y OCULTAR CONTRASEÑA EN CUADRO DE PASSWORD
        if (tf_password.getEchoChar() == '\u2022') { // Si está oculta
        tf_password.setEchoChar((char) 0); // Mostrar la contraseña
        b_showpassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\alan_\\Documents\\NetBeansProjects\\twitterproyect\\src\\main\\Resource\\hidepassword10.png")); // Cambiar icono a "mostrar"
    } else { // Si está visible
        tf_password.setEchoChar('\u2022'); // Ocultar la contraseña
        b_showpassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\alan_\\Documents\\NetBeansProjects\\twitterproyect\\src\\main\\Resource\\showpassword10.png")); // Cambiar icono a "ocultar"
    }
    }//GEN-LAST:event_b_showpasswordActionPerformed

    private void b_crearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearcuentaActionPerformed
// Conexión a la base de datos
Connection conexion = BasededatosTwitter.conectar();
if (conexion != null) {
    System.out.println("El archivo de base de datos se encuentra conectado correctamente.");
} else {
    System.out.println("Error al conectar con base de datos.");
}   

// Tomar los datos
String nombre_usuario = tf_nombreusuario.getText().trim();
String email = tf_correo.getText().trim();
String password = tf_password.getText().trim();

// Verificar que se llenaron los datos
if(nombre_usuario.isEmpty() || email.isEmpty() || password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.");
    return;
}

// Verificar si no existe nombre de usuario
if (verificarExistencianombreusuario(nombre_usuario)) {
    JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe, crea uno nuevo.");
    return;
} else {
    System.out.println("Datos validados.");
}

// Validar la contraseña con los parámetros requeridos
if (!validarContrasena(password)) {
    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres, incluir números, letras y caracteres especiales.");
    return;         
}

if (!esCorreoValido(email)) {
    JOptionPane.showMessageDialog(this, "El formato de correo electrónico es incorrecto.");
    return;
}

// 2. Insertar en la base de datos
try {
    // Adaptamos la consulta para incluir la columna de foto de perfil
    String sql = "INSERT INTO usuarios (nombre_usuario, email, password, foto_perfil) VALUES (?, ?, ?, ?)";
    PreparedStatement ps = conexion.prepareStatement(sql);
    ps.setString(1, nombre_usuario);
    ps.setString(2, email);
    ps.setString(3, password);
    
    // Verificar si se seleccionó una foto
    if (archivoFotoSeleccionada != null) {
        FileInputStream fis = new FileInputStream(archivoFotoSeleccionada);
        ps.setBinaryStream(4, fis, (int) archivoFotoSeleccionada.length());
    } else {
        // Si no se seleccionó imagen, se puede asignar nulo
        ps.setNull(4, java.sql.Types.BLOB);
    }
    
    ps.executeUpdate();
    
    // Si los datos se insertaron correctamente
    JOptionPane.showMessageDialog(this, "¡Usuario creado con éxito!");
    
    // 3. Limpiar los campos
    tf_nombreusuario.setText("");
    tf_correo.setText("");
    tf_password.setText("");
    
    // Cambiar a pantalla de inicio
    PantallaInicio.Home inicio1 = new PantallaInicio.Home();
    inicio1.setVisible(true);
    this.dispose();
    
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Hubo un error al crear su cuenta, intenta más tarde: " + e.getMessage());
} catch (FileNotFoundException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error al cargar la imagen: " + e.getMessage());
}

     
    }//GEN-LAST:event_b_crearcuentaActionPerformed

    private void check_terminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_terminosActionPerformed
        b_crearcuenta.setEnabled(check_terminos.isSelected());//Activar boton de crear cuenta al aceptar terminos.
    }//GEN-LAST:event_check_terminosActionPerformed

    private void b_iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_iniciarsesionActionPerformed
        //Cambiar a pantalla de inicio
        runproyectlogin.Iniciarsesionlogin inicio2 = new runproyectlogin.Iniciarsesionlogin();
        inicio2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_iniciarsesionActionPerformed

    private void tf_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_correoActionPerformed
private File archivoFotoSeleccionada;


    private void btnSeleccionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarFotoActionPerformed
 JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg", "gif"));
    
    int resultado = fileChooser.showOpenDialog(this);
    if (resultado == JFileChooser.APPROVE_OPTION) {
        archivoFotoSeleccionada = fileChooser.getSelectedFile();

        // 1. Crear ImageIcon con la ruta de la imagen
        ImageIcon icono = new ImageIcon(archivoFotoSeleccionada.getAbsolutePath());
        
        // 2. Escalar la imagen al tamaño del JLabel
        Image imagenEscalada = icono.getImage().getScaledInstance(
            lblFoto.getWidth(),
            lblFoto.getHeight(),
            Image.SCALE_SMOOTH
        );
        
        // 3. Crear un nuevo ImageIcon con la imagen escalada
        icono = new ImageIcon(imagenEscalada);

        // 4. Asignar el icono al JLabel
        lblFoto.setIcon(icono);
        lblFoto.setText(""); // Por si tenía algún texto
    }
    }//GEN-LAST:event_btnSeleccionarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_crearcuenta;
    private javax.swing.JButton b_iniciarsesion;
    private javax.swing.JButton b_showpassword;
    private javax.swing.JButton btnSeleccionarFoto;
    private javax.swing.JCheckBox check_terminos;
    private javax.swing.JLabel l1_passwordconditions;
    private javax.swing.JLabel l1_terminos;
    private javax.swing.JLabel l2_passwordconditions;
    private javax.swing.JLabel l2_terminos;
    private javax.swing.JLabel l_correo;
    private javax.swing.JLabel l_fondoiniciosesion;
    private javax.swing.JLabel l_iniciarsesion;
    private javax.swing.JLabel l_nombreusuario;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_textcraeteaccount;
    private javax.swing.JLabel l_texttwitterlogin;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPanel panelderecho_login;
    private javax.swing.JPanel panelizquierdo_login;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_nombreusuario;
    private javax.swing.JPasswordField tf_password;
    // End of variables declaration//GEN-END:variables
}
