/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/*librerias para boton redondeado*/ 
/**
 *
 * @author alan_
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelizquierdo_login = new javax.swing.JPanel();
        l_texttwitterlogin = new javax.swing.JLabel();
        l_fondoiniciosesion = new javax.swing.JLabel();
        panelderecho_login = new javax.swing.JPanel();
        l_textcraeteaccount = new javax.swing.JLabel();
        l_nombreusuario = new javax.swing.JLabel();
        l_correo = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        tf_nombreusuario = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        b_showpassword = new javax.swing.JButton();
        l1_passwordconditions = new javax.swing.JLabel();
        l2_passwordconditions = new javax.swing.JLabel();
        l1_terminos = new javax.swing.JLabel();
        l2_terminos = new javax.swing.JLabel();
        check_terminos = new javax.swing.JCheckBox();
        b_crearcuenta = new javax.swing.JButton();
        l_iniciarsesion = new javax.swing.JLabel();
        b_iniciarsesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelizquierdo_login.setBackground(new java.awt.Color(255, 255, 255));
        panelizquierdo_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_texttwitterlogin.setFont(new java.awt.Font("Times New Roman", 2, 60)); // NOI18N
        l_texttwitterlogin.setForeground(new java.awt.Color(255, 255, 255));
        l_texttwitterlogin.setText("Twitter");
        panelizquierdo_login.add(l_texttwitterlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 40));

        l_fondoiniciosesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondologinvertical.jpg"))); // NOI18N
        panelizquierdo_login.add(l_fondoiniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 270, 460));

        panelderecho_login.setBackground(new java.awt.Color(255, 255, 255));
        panelderecho_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_textcraeteaccount.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l_textcraeteaccount.setText("Create an account");
        panelderecho_login.add(l_textcraeteaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 20, -1, -1));

        l_nombreusuario.setText("Nombre de usuario");
        panelderecho_login.add(l_nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        l_correo.setText("Correo");
        panelderecho_login.add(l_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        l_password.setText("Contraseña");
        panelderecho_login.add(l_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        tf_nombreusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreusuarioActionPerformed(evt);
            }
        });
        panelderecho_login.add(tf_nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 278, -1));
        panelderecho_login.add(tf_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 278, -1));
        panelderecho_login.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 278, -1));

        b_showpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hidepassword10.png"))); // NOI18N
        b_showpassword.setBorder(null);
        b_showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_showpasswordActionPerformed(evt);
            }
        });
        panelderecho_login.add(b_showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 200, 20, 20));

        l1_passwordconditions.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        l1_passwordconditions.setForeground(new java.awt.Color(153, 153, 153));
        l1_passwordconditions.setText("Usa 8 o mas caracteres con una mezcla de numeros, letras y ");
        panelderecho_login.add(l1_passwordconditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        l2_passwordconditions.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        l2_passwordconditions.setForeground(new java.awt.Color(153, 153, 153));
        l2_passwordconditions.setText("caracteres especiales.");
        panelderecho_login.add(l2_passwordconditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        l1_terminos.setForeground(new java.awt.Color(153, 153, 153));
        l1_terminos.setText("Al crear una cuenta aceptas nuestros");
        panelderecho_login.add(l1_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        l2_terminos.setText("Terminos de uso y políticas de privacidad");
        panelderecho_login.add(l2_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        check_terminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_terminosActionPerformed(evt);
            }
        });
        panelderecho_login.add(check_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        b_crearcuenta.setBackground(new java.awt.Color(237, 186, 250));
        b_crearcuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b_crearcuenta.setForeground(new java.awt.Color(255, 255, 255));
        b_crearcuenta.setText("Crear cuenta");
        b_crearcuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_crearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearcuentaActionPerformed(evt);
            }
        });
        panelderecho_login.add(b_crearcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 136, 35));

        l_iniciarsesion.setText("Ya tienes cuenta?");
        panelderecho_login.add(l_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        b_iniciarsesion.setText("Inicia sesión");
        b_iniciarsesion.setBorder(null);
        panelderecho_login.add(b_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelizquierdo_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelderecho_login, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelizquierdo_login, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addComponent(panelderecho_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreusuarioActionPerformed

    private void b_showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_showpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_showpasswordActionPerformed

    private void b_crearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_crearcuentaActionPerformed

    private void check_terminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_terminosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_terminosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_crearcuenta;
    private javax.swing.JButton b_iniciarsesion;
    private javax.swing.JButton b_showpassword;
    private javax.swing.JCheckBox check_terminos;
    private javax.swing.JLabel l1_passwordconditions;
    private javax.swing.JLabel l1_terminos;
    private javax.swing.JLabel l2_passwordconditions;
    private javax.swing.JLabel l2_terminos;
    private javax.swing.JLabel l_correo;
    private javax.swing.JLabel l_fondoiniciosesion;
    private javax.swing.JLabel l_iniciarsesion;
    private javax.swing.JLabel l_nombreusuario;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_textcraeteaccount;
    private javax.swing.JLabel l_texttwitterlogin;
    private javax.swing.JPanel panelderecho_login;
    private javax.swing.JPanel panelizquierdo_login;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_nombreusuario;
    private javax.swing.JPasswordField tf_password;
    // End of variables declaration//GEN-END:variables
}
